name: flake8 Lint

on:
    push:
      branches: main
      paths: [src/**]
    pull_request:
      branches: main
      paths: [src/**]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          run: |
            apk add make
            cd src
            make

      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          commit_message: 'Add Flake8 Linting'
          file_pattern: 'src/*.py'
          branch: main    