name: flake8 Lint

on:
  push:
    branches:
      - main
    paths:
      - src/**

  pull_request:
    branches:
      - main
    paths:
      - src/**

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint

    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y make
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Makefile (if needed)
        run: |
          cd src
          make || echo "Makefile not used"

      - name: Run flake8 Lint
        run: flake8 src --exclude .venv --exclude venv --max-line-length=88 --statistics
