name: flake8 Lint

on:
  push:
    branches:
      - main
    paths:
      - src/**

  pull_request:
    branches:
      - main
    paths:
      - src/**

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint

    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort autoflake

      - name: Auto-Fix with Black (PEP8 Formatter)
        run: black src

      - name: Auto-Fix with isort (Sort Imports)
        run: isort src

      - name: Auto-Fix with Autoflake (Remove Unused Imports & Variables)
        run: autoflake --remove-all-unused-imports --remove-unused-variables --in-place --recursive src

      - name: Run flake8 Lint
        run: flake8 src --max-line-length=88 --statistics
      
      - name: Check for changes
        id: check_changes
        run: |
          git diff --quiet || echo "Code modified"

      - name: Commit and Push Fixes
        if: steps.check_changes.outputs.code_modified != ''
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Auto-fix formatting and linting issues" || exit 0
          git push

